name: Premake on multiple platforms

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop"]

jobs:
  build_windows:
    runs-on: windows-latest
    env:
      SOLUTION_FILE_PATH: .
      BUILD_CONFIGURATION: Release
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          .\Vendor\Binaries\Premake\Windows\premake5.exe --file=Build.lua vs2022
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

      - name: Test
        working-directory: Binaries\windows-x86_64\${{env.BUILD_CONFIGURATION}}\Tests
        run: .\Tests.exe
